<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Upload</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <div class="container">
        <!-- 
            L'attribut "enctype" spécifie comment les données du formulaire doivent être 
            encodées avant d'être envoyées au server lorsque le formulaire est soumis .
            Cet attribut est particulièrement important lorsque vous avez des champs de 
            formulaire  de type "file".

            Lorsque vous définissez 'enctype="multipart/form-data", cela signifie que 
            les données du formulaire seront encodées sous la forme d'un contenu 
            binaire multipart. --

            Ce type d'encodage est utilisé pour les formulaires contenant des --champs de 
            téléchargement de fichiers , car il permet de transférer des fichiers binaires, 
            tels que les images, les vidéos, etc..., en plus --des données de texte.
         -->

        <form action="server.php" method="post" enctype="multipart/form-data">
            <div class="mb-2">
                <label for="file" class="form-label">Importez un fichier !</label>
                <input type="file" class="form-control" id="file" name="photo_profile">
            </div>
            <button class="btn btn-primary" name="submit">Submit</button>
        </form>
    </div>
</body>

</html>