<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Albums</title>
</head>

<body>
    <h1>Modifier un album</h1>
    <pre>
        <?= print_r($album) ?>
    </pre>
    <form action="/update" method="post">
        <input 
        type="hidden" 
        name="id" 
        value="<?php echo $album['id']; ?>">

        <label>Titre: 
            <input type="text"
         name="title" 
         value="<?php echo $album['title']; ?>"></label><br>

        <label>Artiste: 
            <input type="text" 
            name="artiste" 
            value="<?php echo $album['artiste']; ?>"></label><br>

        <input type="submit" value="Mettre à jour">
    </form>
</body>

</html>