<?php
// echo '<pre>';
// print_r($albums);

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des Albums</title>
</head>

<body>
    <h1>Liste des albums :</h1>
    <ul>
        <!-- La liste des albums est générée dynamiquement -->
        <?php foreach ($albums as $album): ?>
            <li>
                <?= $album['title'] ?> - <?= $album['artiste']?>
                <a href="/edit?id=<?php echo $album['id']; ?>">Modifier</a>
                <a href="/delete?id=<?php echo $album['id']; ?>">Suprrimer</a>
            </li>
        <?php endforeach; ?>
    </ul>

    <h2>Ajouter un nouvel album</h2>
    <form action="/add" method="post">
        <label for="#">Title : <input type="text" name="title" placeholder="Titre de l'album"></label>
        <label for="#">Artiste: <input type="text" name="artiste" placeholder="Le nom de l'artiste"></label>
        <input type="submit" value="Ajouter">
    </form>
</body>

</html>