<?php
// echo '<pre>';
// print_r($albums);

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Liste des Albums</title>
    <style>
        body {
            background-color: #212529;
            color: aliceblue;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Liste des albums :</h1>
        <ul>
            <!-- La liste des albums est générée dynamiquement -->
            <?php foreach ($albums as $album): ?>
                <li>
                    <?= $album['title'] ?> -
                    <?= $album['artiste'] ?>
                    <!-- /edit/:id -->
                    <a href="/edit?id=<?= $album['id']; ?>">Modifier</a>
                    <!-- /delete/:id -->
                    <a href="/delete?id=<?= $album['id']; ?>">Suprimer</a>
                </li>
            <?php endforeach; ?>
        </ul>
        <h2>Ajouter un nouvel album</h2>
        <form action="/add" method="post">
            <div class="mb-3">
                <label for="#" class="form-label">Title :
                    <input type="text" name="title" class="form-control" placeholder="Titre de l'album">
                </label>
            </div>
            <div class="mb-3">
                <label for="#" class="form-label">Artiste:
                    <input type="text" name="artiste" class="form-control" placeholder="Le nom de l'artiste">
                </label>
            </div>
            <input type="submit" value="Ajouter">
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>